# ~/nixos-config/modules/desktop/blocklist.nix
{
  config,
  lib,
  pkgs,
  ...
}:

# Blocklist of domains
let
  distractionDomains = [
    "reddit.com"
    "old.reddit.com"
    "www.reddit.com"
    "twitter.com"
    "x.com"
    "www.twitter.com"
    "facebook.com"
    "www.facebook.com"
    "instagram.com"
    "www.instagram.com"
    "tiktok.com"
    "www.tiktok.com"
    "linkedin.com"
    "www.linkedin.com"
    "news.ycombinator.com"
    "lobste.rs"
    "netflix.com"
    "www.netflix.com"
    "twitch.tv"
    "www.twitch.tv"
    "christisking.cc"
    "www.christisking.cc"
    "studio.youtube.com"
    "forum.agoraroad.com"
    "www.forum.agoraroad.com"
    "cbc.ca"
    "www.cbc.ca"
    "www.brutalist.report"
    "brutalist.report"
    "4chan.org"
    "www.4chan.org"
    "boards.4chan.org"
    "i.4cdn.org"
    "s.4cdn.org"
    "a.4cdn.org"
    "t.4cdn.org"
    "is2.4chan.org"
    "sys.4chan.org"
    "i2.4cdn.org"
    "www.cnn.com"
    "cnn.com"
    "bbc.com"
    "www.bbc.com"
    # "youtube.com"
    # "www.youtube.com"
    # "m.youtube.com"
    # "youtu.be"
    "vimeo.com"
    "www.vimeo.com"
    "rumble.com"
    "www.rumble.com"
    "news.google.com"
    "www.theguardian.com"
    "theguardian.com"
    "www.nytimes.com"
    "nytimes.com"
    "www.foxnews.com"
    "foxnews.com"
    "nationalpost.com"
    "www.nationalpost.com"
    "tildes.net"
    "www.tildes.net"
    "slashdot.org"
    "www.slashdot.org"
    "techcrunch.com"
    "www.techcrunch.com"
    "theverge.com"
    "www.theverge.com"
    "wired.com"
    "www.wired.com"
    "arstechnica.com"
    "www.arstechnica.com"
    "thenewstack.io"
    "www.thenewstack.io"
    "dev.to"
    "monkeytype.com"
  ];

in
{
  networking.extraHosts = lib.concatMapStringsSep "\n" (
    domain: "0.0.0.0 ${domain}"
  ) distractionDomains;
}
