color0 #1a1d21
color1 #cdacac
color2 #b8c4b8
color3 #d4ccb4
color4 #b4bcc4
color5 #ccc4b4
color6 #b4c0c8
color7 #f0efeb
color8 #3d424a
color9 #cdacac
color10 #b8c4b8
color11 #d4ccb4
color12 #b4bcc4
color13 #ccc4b4
color14 #b4c0c8
color15 #f5f4f2
background #1a1d21
selection_foreground #1a1d21
cursor #b4bcc4
cursor_text_color #1a1d21
foreground #f0efeb
selection_background #f0efeb
active_border_color #b4bcc4
inactive_border_color #b4c4bc
